# Deneme-1-2 Numpy 

## NumPy Operators

In [1]:
import numpy as np

In [2]:
a = np.arange(4)

In [3]:
a

array([0, 1, 2, 3])

In [4]:
a+10

array([10, 11, 12, 13])

In [5]:
a #numpy is immutable and that is because it is created as a new array

array([0, 1, 2, 3])

In [6]:
a +=100

In [7]:
a

array([100, 101, 102, 103])

In [8]:
l = [0,1,2,3]

In [9]:
[i*10 for i in l]

[0, 10, 20, 30]

In [10]:
a = np.arange(4)

In [11]:
a

array([0, 1, 2, 3])

In [12]:
b = np.array([10,10,10,10])

In [13]:
b

array([10, 10, 10, 10])

In [14]:
a+b

array([10, 11, 12, 13])

In [15]:
a = np.arange(5)

In [16]:
a+20

array([20, 21, 22, 23, 24])

In [17]:
a

array([0, 1, 2, 3, 4])

## Boolean Arrays

In [18]:
a[[0,-1]] #a[0], a[-1]

array([0, 4])

In [19]:
a[[True, False, False, True, False]]

array([0, 3])

In [20]:
a

array([0, 1, 2, 3, 4])

In [21]:
a>=2

array([False, False,  True,  True,  True])

In [22]:
a[a>=2]

array([2, 3, 4])

In [23]:
a.mean()

2.0

In [24]:
print(a <=3)

[ True  True  True  True False]


## Linear Algebra

In [26]:
A = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

In [27]:
B = np.array([
    [6,5],
    [4,3],
    [2,1]
])

In [28]:
A.dot(B)

array([[20, 14],
       [56, 41],
       [92, 68]])

In [29]:
A @ B

array([[20, 14],
       [56, 41],
       [92, 68]])

In [30]:
B.T

array([[6, 4, 2],
       [5, 3, 1]])

In [31]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [32]:
B.T @ A

array([[36, 48, 60],
       [24, 33, 42]])

## Useful Numpy Functions

### random

In [35]:
np.random.random(size=2)

array([0.16958806, 0.80426188])

In [40]:
np.random.normal(size=2)

array([-0.04276197, -0.21525267])

In [44]:
np.random.rand(2,5)

array([[0.48878081, 0.24482398, 0.61893947, 0.44265773, 0.01088336],
       [0.51772765, 0.39465568, 0.25235426, 0.48487816, 0.53946909]])

### arange

In [45]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [46]:
np.arange(5,10)

array([5, 6, 7, 8, 9])

In [48]:
np.arange(0, 2, .1)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. , 1.1, 1.2,
       1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9])

### reshape

In [58]:
np.arange(20).reshape(4,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [59]:
np.arange(10).reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [60]:
np.arange(10).reshape(5,2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

### linspace

In [65]:
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [67]:
np.linspace(0, 1, 20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [68]:
np.linspace(0, 1, 20, False)

array([0.  , 0.05, 0.1 , 0.15, 0.2 , 0.25, 0.3 , 0.35, 0.4 , 0.45, 0.5 ,
       0.55, 0.6 , 0.65, 0.7 , 0.75, 0.8 , 0.85, 0.9 , 0.95])

### zeros, ones, empty

In [70]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [72]:
np.zeros((3, 3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [73]:
np.zeros((3, 3), dtype=np.int)

/var/folders/0g/d_1ygn0x68n1cv80st0ppctw0000gn/T/ipykernel_13499/383259716.py:1: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  np.zeros((3, 3), dtype=np.int)


array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [74]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [76]:
np.ones((3, 3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [77]:
np.empty(5)

array([1., 1., 1., 1., 1.])

In [78]:
np.empty((2,2))

array([[0.25, 0.5 ],
       [0.75, 1.  ]])

### identity and eye

In [79]:
np.identity(2)

array([[1., 0.],
       [0., 1.]])

In [80]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [81]:
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [82]:
np.eye(8,4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [83]:
np.eye(8, 4, k=1)

array([[0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [84]:
np.eye(8, 4, k=-3)

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.]])

In [85]:
"Hello World"[6]

'W'