# This is a Python Tutorial

## Variables

In [9]:
x=3.4

%whos

Variable   Type       Data/Info
-------------------------------
A          ndarray    100: 100 elems, type `int32`, 400 bytes
la         module     <module 'numpy.linalg' fr<...>py\\linalg\\__init__.py'>
np         module     <module 'numpy' from 'C:\<...>ges\\numpy\\__init__.py'>
os         module     <module 'os' from 'C:\\Us<...>n\\Python39\\lib\\os.py'>
sys        module     <module 'sys' (built-in)>
x          float      3.4


In [10]:
a,b,c,d = 3,4,5.0,7

In [11]:
print(type(x))

<class 'float'>


In [12]:
abcd = 556.2

print(type(abcd))

del abcd

%whos

<class 'float'>
Variable   Type       Data/Info
-------------------------------
A          ndarray    100: 100 elems, type `int32`, 400 bytes
a          int        3
b          int        4
c          float      5.0
d          int        7
la         module     <module 'numpy.linalg' fr<...>py\\linalg\\__init__.py'>
np         module     <module 'numpy' from 'C:\<...>ges\\numpy\\__init__.py'>
os         module     <module 'os' from 'C:\\Us<...>n\\Python39\\lib\\os.py'>
sys        module     <module 'sys' (built-in)>
x          float      3.4


## Operators

In [13]:
%whos

Variable   Type       Data/Info
-------------------------------
A          ndarray    100: 100 elems, type `int32`, 400 bytes
a          int        3
b          int        4
c          float      5.0
d          int        7
la         module     <module 'numpy.linalg' fr<...>py\\linalg\\__init__.py'>
np         module     <module 'numpy' from 'C:\<...>ges\\numpy\\__init__.py'>
os         module     <module 'os' from 'C:\\Us<...>n\\Python39\\lib\\os.py'>
sys        module     <module 'sys' (built-in)>
x          float      3.4


## Bool

In [14]:
v = True
y = True
z = False

In [15]:
%whos

Variable   Type       Data/Info
-------------------------------
A          ndarray    100: 100 elems, type `int32`, 400 bytes
a          int        3
b          int        4
c          float      5.0
d          int        7
la         module     <module 'numpy.linalg' fr<...>py\\linalg\\__init__.py'>
np         module     <module 'numpy' from 'C:\<...>ges\\numpy\\__init__.py'>
os         module     <module 'os' from 'C:\\Us<...>n\\Python39\\lib\\os.py'>
sys        module     <module 'sys' (built-in)>
v          bool       True
x          float      3.4
y          bool       True
z          bool       False


In [16]:
print(v and y)
print(v and z)
print(z and v)

True
False
False


In [17]:
d = v or z 
print(d)

True


In [18]:
not(v)

False

In [19]:
not(y)

False

In [20]:
t = not(z)
print(t)

True


In [21]:
not((a and b) or (c or d))

False

In [22]:
G = divmod(22,10)

In [23]:
type(G)

tuple

In [24]:
G[0]

2

In [25]:
G[1]

2

In [26]:
isinstance(3.4,float)

True

In [27]:
isinstance(2.1,int)

False

pow(x,y,z) x raise to the power y and remainder by z

In [28]:
pow(2,3,4)

0

In [29]:
pow(2,4,5)

1

In [30]:
x = input("Enter a number : ")

In [31]:
x = int(x)

ValueError: invalid literal for int() with base 10: ''

In [ ]:
print(type(x))

<class 'int'>


In [ ]:
a = float(input("Enter a real number"))

In [ ]:
pow?

Signature: pow(base, exp, mod=None)
Docstring:
Equivalent to base**exp with 2 arguments or base**exp % mod with 3 arguments

Some types, such as ints, are able to use a more efficient algorithm when
invoked using the three argument form.
Type:      builtin_function_or_method


In [ ]:
pow?

Signature: pow(base, exp, mod=None)
Docstring:
Equivalent to base**exp with 2 arguments or base**exp % mod with 3 arguments

Some types, such as ints, are able to use a more efficient algorithm when
invoked using the three argument form.
Type:      builtin_function_or_method


In [ ]:
help(input)

Help on method raw_input in module ipykernel.kernelbase:

raw_input(prompt='') method of ipykernel.ipkernel.IPythonKernel instance
    Forward raw_input to frontends
    
    Raises
    ------
    StdinNotImplementedError if active frontend doesn't support stdin.



In [ ]:
a = int(input("Enter Marks : "))
if a >= 85:
    print("A Grade")
elif (a<85) and (a>=80):
    print("A- Grade")
elif (a<80) and a>=75:
    print("B Grade")
elif (a<75) and (a>=70):
    print("B- Grade")
else:
    print("Below Average")

B Grade


In [ ]:
n = int(input())
i = 1
while i < n:
    print(i**2)
    print("This is iteration number :", i)
    i += 1
print("Loop is done")


ValueError: invalid literal for int() with base 10: ''

In [ ]:
L = []
for i in range(10):
    print(i+1)
    L.append(i**2)
print(L)

1
2
3
4
5
6
7
8
9
10
[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]


In [ ]:
L = []
for i in range(0,10,2):
    print(i)
    L.append(i**2)
print(L)

0
2
4
6
8
[0, 4, 16, 36, 64]


In [ ]:
L = [1, 2, 4, -5, 7, 9, 3, 2]

m = L[0]
idx = 0
c = 0
for i in L:
    if i < m:
        m = i
        idx = c
    c += 1
print(idx, m)


3 -5


In [ ]:
L = [1, 2, 4, -5, 7, 9, 3, 2]
for j in range(len(L)):
    m = L[j]
    idx = j
    c = j
    for i in range(j, len(L)):
        if L[i] < m:
            m = L[i]
            idx = c
        c += 1
    tmp = L[j]
    L[j] = m
    L[idx] = tmp
print(L)


[-5, 1, 2, 2, 3, 4, 7, 9]


In [ ]:
def printSuccess():
    """ This function is doing nothing except printing a message.
    That message is...
    """
    print("Hello")

In [ ]:
printSuccess?

Signature: printSuccess()
Docstring:
This function is doing nothing except printing a message.
That message is...
File:      c:\users\m_ali\appdata\local\temp\ipykernel_15736\1028495564.py
Type:      function


In [ ]:
printSuccess()

Hello


## Functions(input arguments)

In [ ]:
def printMsg(msg):
    """The function prints the message supplied by the user
    or print that msg is not in the form of string"""

    if isinstance(msg,str):
        print(msg)
    else:
        print("Your input argument is not a string")
        print("Here is the type of what you have supplied :", type(msg))

In [ ]:
printMsg("Hi there")

Hi there


In [ ]:
printMsg(5)

Your input argument is not a string
Here is the type of what you have supplied : <class 'int'>


In [ ]:
def myadd(a, b):
    sumValue = a+b
    return sumValue

7


In [ ]:
d = myadd(3, 4)
print(d)

7


In [ ]:
variableOutsideTheFunction = 3

In [ ]:
def g():
    variableOutsideTheFunction = 5
    print(variableOutsideTheFunction)

In [ ]:
g()

5


In [ ]:
print(variableOutsideTheFunction)

3


In [ ]:
def r():
    a=5
    b=7
    d="something"
    return a,b,d

In [ ]:
x,y,z = r()
print(x,y,z)

5 7 something


In [ ]:
def myAddUniversal(*args):
    s=0
    for i in range(len(args)):
        s += args[i] # s= s+args[i]
    return s 

In [ ]:
print(myAddUniversal(2,3,4,11))

20


In [ ]:
def printAllVariableNamesAndValues(**args):
    for x in args:
        print("Variable Name is:", x," And Value is :", args[x])

In [ ]:
printAllVariableNamesAndValues(a =3, b="B", c="CCC", y=6.7)

Variable Name is: a  And Value is : 3
Variable Name is: b  And Value is : B
Variable Name is: c  And Value is : CCC
Variable Name is: y  And Value is : 6.7


### Functions(Default Values)

In [ ]:
def gg(s=4):
    print(s)

In [ ]:
gg()

4


In [ ]:
gg(56)

56


In [ ]:
L = [1, 2, 4]
L2 = L
L2[0] = -9
print(L)


[-9, 2, 4]


In [ ]:
def ff(L=[1,2]):
    for i in L:
        print(i)

In [ ]:
L2 = [12,3,4]
ff()

1
2


In [ ]:
ff(L2)

12
3
4


In [ ]:
ff()

1
2


## Modules

In [ ]:
import sys
sys.path.append('C:/Users/M_Ali/Desktop/ABC')

In [ ]:
#import my_universal_function as myf
from my_universal_function import addAllNumerics

In [ ]:
#myf.addAllNumerics(6,7,8,9)
addAllNumerics(6,7,8,9)

30

In [ ]:
def findMin(L, startIndx):
    m = L[startIndx]
    idx = startIndx
    
    for i in range(startIndx,len(L)):
        x = [L]
        if x < m:
            m = x
            idx = i
        else:
            pass
    return m, idx


In [ ]:
a,b= findMin([2,3,4,0,9])
print(a,b)

0 3


In [ ]:
def swapValues(L, idx1, idx2):
    tmp = L[idx1]
    L[idx1]= L[idx2]
    L[idx2]=tmp
    return L

L = [2,3,6,7]
L2 = swapValues(L,1,3)
print(L2)

[2, 7, 6, 3]


In [ ]:
from my_universal_function import checkIfNotNumeric

def sortList(L):
    if not(checkIfNotNumeric2(L)):
        print(" Error: List does not contain numeric values")
        return
    else:
        c = 0
        for x in L:
            m,idx=findMin(L,c)
            L = swapValues(L,c,idx)
            c+=1
        return L




In [ ]:
def checkIfNotNumeric2(L):
    for x in L:
        if not(isinstance(x,(int,float))):
            return False
    return True

In [ ]:
print(checkIfNotNumeric2([2,1,5,3,9,17]))

True


In [ ]:
L2 = sortList([2,1,5,3,-8,17])
print(L2)

NameError: name 'sortList' is not defined

In [ ]:
price = 12
s = "The price of this book"
v = s + ' is: ' + str(price)
print(v)
print(s,"is:",price)

The price of this book is: 12
The price of this book is: 12


In [ ]:
print(s[5])

r


In [ ]:
s[3:9]

' price'

In [ ]:
s[-1]

'k'

In [ ]:
s[0:12:2] #[start:end:step]

'Tepieo'

In [ ]:
s[:12]

'The price of'

In [ ]:
s[3:]

' price of this book'

In [ ]:
print("We are learning \"string\" here")

We are learning "string" here


In [ ]:
print("c:\name\drive")

c:
ame\drive


In [ ]:
print(r"c:\name\drive")

c:\name\drive


# Data Structures

In [ ]:
L = [1,3,4.9,"name",3] #ordered, changeable, duplicates
T = (1,3,4.9,"name",3) #ordered, unchangeable, duplicates
S = {1,3,4.9,"name",3} #unordered, addable/removable, no duplicates
D = {23:"twothree",'B':43, 'C':'CCD'} #unordered, changeable, no duplicates

In [ ]:
print("The type of L is ", type(L))
print("The type of T is ", type(T))
print("The type of S is ", type(S))
print("The type of D is ", type(D))

The type of L is  <class 'list'>
The type of T is  <class 'tuple'>
The type of S is  <class 'set'>
The type of D is  <class 'dict'>


In [ ]:
print(L[1])
print(T[1])
print(3 in S)
print(D[23])

3
3
True
twothree


In [ ]:
print(D['B'])

43


In [ ]:
S 

{1, 3, 4.9, 'name'}

In [ ]:
L = L + ["how", "are", 6,"you"]

In [ ]:
L

[1, 3, 4.9, 'name', 3, 'how', 'are', 6, 'you']

In [ ]:
L.append(6.8)

In [ ]:
L

[1, 3, 4.9, 'name', 3, 'how', 'are', 6, 'you', 6.8]

In [ ]:
T2 = ('a','b', 45)
T3 = T+T2

In [ ]:
T3

(1, 3, 4.9, 'name', 3, 'a', 'b', 45)

In [ ]:
S.add(56)

In [ ]:
S

{1, 3, 4.9, 56, 'name'}

In [ ]:
S.update({23,"game",1})

In [ ]:
S

{1, 23, 3, 4.9, 56, 'game', 'name'}

In [ ]:
D['newKey']="newValue"

In [ ]:
D

{23: 'twothree', 'B': 43, 'C': 'CCD', 'newKey': 'newValue'}

In [ ]:
del L[3]

In [ ]:
L

[1, 3, 4.9, 3, 'how', 'are', 6, 'you', 6.8]

In [ ]:
S.remove('game')

In [ ]:
S

{1, 23, 3, 4.9, 56, 'name'}

In [ ]:
help(L.append)

Help on built-in function append:

append(object, /) method of builtins.list instance
    Append object to the end of the list.



In [ ]:
L.pop?

Signature: L.pop(index=-1, /)
Docstring:
Remove and return item at index (default last).

Raises IndexError if list is empty or index is out of range.
Type:      builtin_function_or_method


In [ ]:
L.reverse()

In [ ]:
L

[6.8, 'you', 6, 'are', 'how', 3, 4.9, 3, 1]

In [ ]:
D2= {'A':L,'B':T,'C':S,'D':D}

In [ ]:
D2['A'][3]

'are'

In [ ]:
K = D2['D']

In [ ]:
K

{23: 'twothree', 'B': 43, 'C': 'CCD', 'newKey': 'newValue'}

In [ ]:
for x in K:
    print(x,K[x])

23 twothree
B 43
C CCD
newKey newValue


In [ ]:
L3=[L,T,D,23,"game"]

In [ ]:
type(L3[2])

dict

In [ ]:
L3=[x**2 for x in range(10)]

In [ ]:
L3

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]

In [ ]:
type(L3)

list

In [ ]:
"""Let say you are a teacher and you have different student records
containing id of a student and the marks list in each subject
where different students have taken different number of subjects.
All these records are in hard copy. You want to enter all the data in computer
and want to compute the average marks of each student and display"""

def getDataFromUser():
    D = {}
    while True:
        studentId = input("Enter student ID: ")
        marksList = input("Enter the marks by comma seperated values: ")
        moreStudents = input('Enter "no" to quit insertion')
        if studentId in D:
            print(studentId,"is already inserted")
        else:
            D[studentId] = marksList.split(",")
        if moreStudents.lower()=="no":
            return D

In [ ]:
studentData = getDataFromUser()

In [ ]:
print(studentData)

{'12': ['45', '55', '66', '77']}


In [ ]:
def getAvgMarks(D):
    avgMarks = {}
    for x in D:
        L = D[x]
        s = 0
        for marks in L:
            s += int(marks)
        avgMarks[x] = s/len(L)
    return avgMarks

In [ ]:
avgM = getAvgMarks(studentData)

In [ ]:
print(avgM)

None


In [ ]:
for x in avgM:
    print("Student :", x, "got avg Marks as:", avgM[x])

TypeError: 'NoneType' object is not iterable

In [ ]:
# Numpy

In [ ]:
import numpy as np

In [ ]:
a = np.array([1,2,3,5,7], dtype='i')

In [ ]:
b= np.array((2,3,5), dtype='f')

In [ ]:
print(a)

[1 2 3 5 7]


In [ ]:
type(a)

numpy.ndarray

In [ ]:
a.dtype

dtype('int32')

In [ ]:
b.dtype

dtype('float32')

In [ ]:
a = np.array([[1,2,3],[4,5,6]])

In [ ]:
a.ndim

2

In [ ]:
a[0,2]

3

In [ ]:
a.size

6

In [ ]:
import numpy as np

In [ ]:
A = np.arange(100)

In [ ]:
print(A)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]


In [ ]:
B = np.arange(20,100)

In [ ]:
print(B)

[20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43
 44 45 46 47 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67
 68 69 70 71 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91
 92 93 94 95 96 97 98 99]


In [ ]:
C = np.arange(20,100,3) #for i in range(20,100,3)

In [ ]:
print(C)

[20 23 26 29 32 35 38 41 44 47 50 53 56 59 62 65 68 71 74 77 80 83 86 89
 92 95 98]


In [ ]:
print(list(range(0,10)))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


In [ ]:
np.random.permutation
np.reshape

<function numpy.reshape(a, newshape, order='C')>

## Numpy Slicing

In [ ]:
A = np.arange(100)

In [ ]:
b = A[3:10]

print(b)

[3 4 5 6 7 8 9]


In [ ]:
b[0] = -1200

In [ ]:
b

array([-1200,     4,     5,     6,     7,     8,     9])

In [ ]:
A


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [ ]:
b = A[3:10].copy() # if you change the b now A is going to be same

In [ ]:
A[::5]

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80,
       85, 90, 95])

In [ ]:
A[::-5]

array([99, 94, 89, 84, 79, 74, 69, 64, 59, 54, 49, 44, 39, 34, 29, 24, 19,
       14,  9,  4])

In [ ]:
A

NameError: name 'A' is not defined

In [ ]:
idx = np.argwhere(A==-1200)[0]

NameError: name 'np' is not defined

In [ ]:
idx

NameError: name 'idx' is not defined

In [ ]:
idx = np.argwhere(A==-1200)[0][0]

NameError: name 'np' is not defined

In [ ]:
idx

3

In [ ]:
A[idx]

-1200

In [ ]:
A[idx] = 3

NameError: name 'idx' is not defined

In [37]:
A

array([[5., 1., 7., 5.],
       [6., 2., 4., 9.],
       [5., 6., 4., 9.],
       [4., 3., 5., 5.],
       [1., 9., 8., 1.]])

In [38]:
A = np.round(10*np.random.rand(5,4))

In [39]:
A

array([[10.,  6.,  4.,  8.],
       [ 9.,  1.,  9.,  6.],
       [ 6.,  2.,  7.,  4.],
       [ 9.,  3.,  9.,  7.],
       [ 0.,  6.,  4.,  3.]])

In [40]:
A[1,2]

9.0

In [42]:
A[1,:]

array([9., 1., 9., 6.])

In [41]:
A[:,1]

array([6., 1., 2., 3., 6.])

In [43]:
A[1:3,2:4]

array([[9., 6.],
       [7., 4.]])

In [44]:
A.T

array([[10.,  9.,  6.,  9.,  0.],
       [ 6.,  1.,  2.,  3.,  6.],
       [ 4.,  9.,  7.,  9.,  4.],
       [ 8.,  6.,  4.,  7.,  3.]])

In [45]:
import numpy.linalg as la

In [46]:
la.inv(np.random.rand(3,3))

array([[ 5.31206451, -0.20344757, -3.22964028],
       [-3.78330282, -3.46691444,  5.58295802],
       [-3.36740476,  2.37091734,  1.44784167]])

In [47]:
A

array([[10.,  6.,  4.,  8.],
       [ 9.,  1.,  9.,  6.],
       [ 6.,  2.,  7.,  4.],
       [ 9.,  3.,  9.,  7.],
       [ 0.,  6.,  4.,  3.]])

In [50]:
A.sort(axis=1)

In [51]:
A

array([[ 0.,  1.,  3.,  4.],
       [ 2.,  4.,  4.,  6.],
       [ 3.,  6.,  7.,  9.],
       [ 6.,  7.,  9.,  9.],
       [ 6.,  8.,  9., 10.]])

In [54]:
A = np.arange(100)

In [55]:
B = A[[3,5,6]]

In [56]:
B

array([3, 5, 6])

In [57]:
A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [58]:
B = A[A<40]

In [59]:
B

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39])

In [61]:
B = A[(A<40)&(A>30)]

In [62]:
B

array([31, 32, 33, 34, 35, 36, 37, 38, 39])