In [1]:
import numpy as np

In [3]:
np.array([1, 2, 3.2, 14.5]) # numpy pushes the values in a list to the same type

array([ 1. ,  2. ,  3.2, 14.5])

In [4]:
np.zeros(5, dtype=int) # creates an array of 5 zeros

array([0, 0, 0, 0, 0])

In [5]:
np.ones((3, 3), dtype=int) # creates an array of 3x3 ones

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [6]:
np.full((3, 3), 5) # creates an array of 3x3 filled with 5

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [7]:
np.arange(0, 10, 2) # creates an array of 0 to 10 with steps of 2

array([0, 2, 4, 6, 8])

In [10]:
np.linspace(0, 10, 5) # creates an array of 5 evenly spaced numbers between 0 and 10

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [11]:
np.random.normal(10, 2, 5) # creates an array of 5 normally distributed numbers with mean 10 and standard deviation 2

array([12.68444391,  6.61990651, 10.20359599, 11.94736721,  7.81073831])

In [12]:
np.random.randint(0, 10, (3,3)) # creates an array of 3x3 random integers between 0 and 10

array([[9, 6, 1],
       [8, 9, 2],
       [8, 4, 8]])