In [2]:
import numpy as np

In [3]:
np.array([1, 2, 3.2, 14.5]) # numpy pushes the values in a list to the same type

array([ 1. ,  2. ,  3.2, 14.5])

In [4]:
np.zeros(5, dtype=int) # creates an array of 5 zeros

array([0, 0, 0, 0, 0])

In [5]:
np.ones((3, 3), dtype=int) # creates an array of 3x3 ones

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [6]:
np.full((3, 3), 5) # creates an array of 3x3 filled with 5

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [7]:
np.arange(0, 10, 2) # creates an array of 0 to 10 with steps of 2

array([0, 2, 4, 6, 8])

In [10]:
np.linspace(0, 10, 5) # creates an array of 5 evenly spaced numbers between 0 and 10

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [11]:
np.random.normal(10, 2, 5) # creates an array of 5 normally distributed numbers with mean 10 and standard deviation 2

array([12.68444391,  6.61990651, 10.20359599, 11.94736721,  7.81073831])

In [12]:
np.random.randint(0, 10, (3,3)) # creates an array of 3x3 random integers between 0 and 10

array([[9, 6, 1],
       [8, 9, 2],
       [8, 4, 8]])

## Numpy Array Specs

* **ndim:** dimension number
* shape: dimension info
* size: overall element number
* dtype: array data type

In [3]:
np.random.randint(10, size=10)

array([8, 4, 0, 3, 9, 9, 3, 5, 4, 6])

In [4]:
a = np.random.randint(10, size=10)

In [5]:
a.ndim

1

In [6]:
a.shape

(10,)

In [7]:
a.size

10

In [8]:
a.dtype

dtype('int64')

In [9]:
b = np.random.randint(10, size=(3,3))

In [10]:
b

array([[2, 5, 9],
       [7, 5, 7],
       [5, 8, 8]])

In [11]:
b.ndim

2

In [12]:
b.shape

(3, 3)

In [14]:
b.size

9

In [21]:
# reshape an array
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [22]:
np.arange(1,10).reshape((3,3))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [23]:
a = np.arange(1,10)

In [24]:
a.ndim # one dimensional array(vector)

1

In [25]:
b = a.reshape((1,9))
b

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [26]:
b.ndim # two dimensional array(matrix)

2

In [27]:
#concatenate arrays
a = np.arange(1,3)
b = np.arange(3,6)

In [28]:
np.concatenate((a,b))

array([1, 2, 3, 4, 5])

In [32]:
#concatenate two arrays
a = np.array([[1,2,3],[4,5,6]])

In [33]:
np.concatenate([a,a])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [34]:
np.concatenate((a,a), axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])